.Dd November 2, 2022
.Dt PASID 1
.Sh NAME
.Nm pasid
.Nd list & query pulseaudio sink ids
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Fl q Ar query
.Sh DESCRIPTION
The
.Nm
utility lets you list and query pulseaudio sink ids.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl q
get the sink id of the application that matches the query
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It list all input sinks
pasid
.It increase the volume of the librewolf application by 5 percent
pasid -q librewolf | xargs -I{} pactl set-sink-input-volume "{}" +5%
.El
.Sh EXIT STATUS
.Bl -tag -width indent
.It 0
the program terminated successfully
.It 1
an error occurred
.It 2
the specified query did not match any application
.El
.Sh SEE ALSO
.Xr pulseaudio 1
.Xr pactl 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/pasid/issues
